version: "3.7"

services:
  api-feiras-livres:
    container_name: api-feiras-livres
    build:
      context: ../
      dockerfile: ../../Dockerfile
    ports:
      - "8080:8080"
    networks:
      - network-feiras-livres
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8
    networks:
      - network-feiras-livres
    ports:
      - 3306:3306
    command: ['--secure-file-priv=/var/lib/']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=feiras-livres

networks:
  network-feiras-livres:
    driver: bridge